### ISSUE TITLE
Create start migration for main table of databases

### ISSUE THREAD

**Issue by kyrylo-permiakov** [UjinPererva/data-storage-management#4]
надо структуру продумать, кроме очевидного и замутить миграцию

**Comment by UjinPererva** [comment]
только же чувак. Суть идеи в том, чтоб управлять не табличками, а именно базами данными. Я знаю только то, что можно подключится к определенной базе данных, а уже в ней управлять таблицами.
Надо бы найти можно ли реализовать подключение к СУБД, а там уже ебошить, что душе угодно или нужно именно базу данных указывать

**Comment by UjinPererva** [comment]
таблица баз данных по идеи хранит все настройки к базам данных, чтоб пыха могла подключится к ней, плюс пользователя создателя бд, субд, время добавления, время обновления
